### ISSUE TITLE
Parallel scalability benchmarks?

### ISSUE THREAD

**Issue by milancurcic** [dionhaefner/veros#37]
Hi Dion,

Nice work with Veros! I skimmed through the docs and your slides from AMS. I have a few questions:

* Can Veros run in distributed memory mode (beyond a single node)?
* Have you done any parallel scalability benchmarks -- even if only for shared memory?

I am looking at your [benchmarks](https://veros.readthedocs.io/more/benchmarks.html) for different problem sizes, and one thing confuses me. For 1e7 elements, you get, for example for Veros numpy, 65 s for a 4-core system and 90 s for a 24-core system + GPU. Am I not reading this correctly? This seems to me like that performance is worse with more cores, but I cannot imagine that would be the case.

**Comment by dionhaefner** [comment]
Hey!

> Can Veros run in distributed memory mode (beyond a single node)?

Currently, no. It is our philosophy to handle all parallelism in the backend, and unless we implement bindings to suitable distributed library, we will only support shared memory architectures. I am currently evaluating whether we can modify `dask.array` to fit our needs, but it will take a while.

> Have you done any parallel scalability benchmarks -- even if only for shared memory?

Yes! Those were the ones you looked at. I can understand that they may seem confusing if you're not familiar with our backends. NumPy is a serial library, so the number of cores doesn't matter, and architecture 1 has better single-core performance, so NumPy runs a bit faster (the same applies for the serial Fortran backend). Bohrium and Fortran + MPI are parallelized, that's why they run significantly faster on the 24-core architecture.

The takeaway message from those benchmarks is that NumPy performs better than Bohrium for small setups, but for large problems the benefits are huge (and performance is in the same order of magnitude as the MPI-parallelized Fortran library).

**Comment by milancurcic** [comment]
OK, now I see what you're saying. Basically, on diagram II, the horizontal lines of Bh GPU and Bh CPU in the 1e3 - 1e6 elements range implies scalability...

I think it would be helpful to see t(1) / t(n) for n = 1, 2, 4, ..., 24 cores.
